# modules enabled
[character]
error_symbol = "✗"
use_symbol_for_status = true

[time]
disabled = false

# modules disabled
[dotnet]
disabled = true

[golang]
disabled = true

[kubernetes]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[python]
disabled = true
