# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# editorconfig
# editorconfig for vim
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# markdown
# syntax file type markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
	source ~/.config/nvim/plugins/vim-markdown.vim
'''

# preview markdown on browser
[[plugins]]
repo = 'previm/previm'
hook_add = '''
	source ~/.config/nvim/plugins/previm/previm.vim
'''

# fish
# syntax file type fish
[[plugins]]
repo = 'dag/vim-fish'

# toml
# syntax file type toml
[[plugins]]
repo = 'cespare/vim-toml'

# terraform
# syntax file type terraform
[[plugins]]
repo = 'hashivim/vim-terraform'
hook_add = '''
	let g:terraform_fmt_on_save = 1
'''

# go
# go command use as vim command :GoBuild, :GoInstall
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
	source ~/.config/nvim/plugins/vim-go.vim
'''

# color sheme
[[plugins]]
repo = 'dracula/vim'
