# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# complement and lsp client
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

# color sheme
[[plugins]]
repo = 'dracula/vim'

# lean & mean status/tabline
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['dracula/vim']

# auto close parentheses
[[plugins]]
repo = 'cohama/lexima.vim'

# set indent line
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  set list listchars=tab:\|\
'''

# editorconfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# preview markdown on terminal
# nmap pv :Previewmarkdown<Return>
[[plugins]]
repo = 'skanehira/preview-markdown.vim'
hook_add = '''
  source ~/.config/nvim/plugins/preview-markdown.vim
'''

# preview markdown on browser
# nmap pb :PrevimOpen<Return>
[[plugins]]
repo = 'previm/previm'
hook_add = '''
  source ~/.config/nvim/plugins/previm/previm.vim
'''

# easy motion
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  source ~/.config/nvim/plugins/vim-easymotion.vim
'''

# commented out
[[plugins]]
repo = 'tomtom/tcomment_vim'

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# fish
# fir syntax hilighting
[[plugins]]
repo = 'dag/vim-fish'

# json
# for let g:vim_json_syntax_conceal = 0
[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

# terraform
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['hcl', 'tf', 'tfvars']
hook_add = '''
  let g:terraform_fmt_on_save = 1
'''
