# modules
[character]
error_symbol = "✗"
use_symbol_for_status = true

[dotnet]
disabled = true

[golang]
disable = true

[java]
disable = true

[nodejs]
disable = true

[package]
disable = true

[python]
disable = true

[time]
disabled = false

[username]
disabled = true
