name: CI

on:
  push:
    branches:
    - master
    paths:
    - '**.sh'

jobs:
  shellcheck:
    runs-on: macOS-10.14
    
    steps:
    - uses: docker://shellcheck-alpine:v0.7.0
    
    - name: Check scripts with shellcheck
      run: |
        find . -type f -name '*.sh' | wc -l
        find . -type f -name '*.sh' | xargs shellcheck --external-sources
