name: CI

on:
  pull_request:
    types: [opened, synchronize]
    paths:
    - '**.sh'

jobs:
  shellcheck:
    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@master
    
    - name: Check scripts with shellcheck
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} \
          --diff-filter=AM \
          --name-only -- '*.sh' \
          | while read script ; do \
              shellcheck ${EXCLUDE_OPTS:+-e ${EXCLUDE_OPTS}} $script || \
              touch error.$$ ; \
            done
        test ! -e error.$$
