name: CI

on:
  push:
    branches:
    - master
    paths:
    - '**.sh'

jobs:
  shellcheck:
    name: shellcheck
    runs-on: macOS-10.14
    steps:
    - name: Check scripts with shellcheck
      uses: docker://shellcheck-alpine:v0.7.0
      run: |
        find . -type f -name '*.sh' | wc -l
        find . -type f -name '*.sh' | xargs shellcheck --external-sources
